[project]
name = "gritai-mcp-server-course"
version = "0.1.0"
description = "Demo project of MCP servers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
    "psycopg2>=2.9.10",
    "psycopg2-binary>=2.9.10",
]
